# Generated by Django 5.2.8 on 2025-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='venus',
            new_name='venue',
        ),
    ]
